name: Main workflow

on: [push,workflow_dispatch]

jobs:          
  build:
    runs-on: ubuntu-latest
    env:
      SOLC_HELP_REGEXP: "^solc, the Solidity commandline compiler.*$"
      TONOS_CLI_HELP_REGEXP: "^.*TONLabs console tool for TON.*$"
      TONOS_LINKER_HELP_REGEXP: "^.*Linker for TVM assembly.*$"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - uses: ton-actions/setup-tools@v1
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build SetcodeMultisigWallet.sol
        run: |  
          solc solidity/setcodemultisig/SetcodeMultisigWallet.sol
          
      - uses: actions/upload-artifact@v2
        with:
          name: SetcodeMultisigWallet
          path: solidity/setcodemultisig/*